Add Method List.copyWithInsertAll()
Innim/dart_list_extensions pull request #4
Opened 2021-10-14 14:26 UTC by mongugay

2021-10-14 14:34 UTC, greymag requested changes
Не хватает:

- [x] Тестов на новый метод 
- [x] Описания в README

2021-10-14 14:34 UTC, greymag commented on lib/src/list_extensions.dart
> +  /// If current list is `null` - copy of list [elements] will be created.
Если передать какой-то неподходящий индекс, то будет исключение - это нужно указать в доке.

2021-10-15 07:41 UTC, greymag requested changes

2021-10-15 07:41 UTC, greymag commented on README.md
> +* `copyWithInsertAll()` -Copy current list with adding all [elements] at the position of new list.
```suggestion
* `copyWithInsertAll()` - Copy current list with adding all elements at the provided position of new list.
```

Тут получается же не может быть теперь null)

2021-10-15 07:41 UTC, greymag commented on lib/src/list_extensions.dart
> +  /// If current list is `null` - copy of list [elements] will be created.
```suggestion
```

2021-10-15 07:41 UTC, greymag commented on test/list_extensions_test.dart
> +
Первую/последнюю проверил - хорошо, еще на среднюю какую-нибудь допиши

2021-10-15 07:41 UTC, greymag commented on test/list_extensions_test.dart
> +
Еще нужен тест на добавление в null список в ненулевую позицию

2021-10-15 07:50 UTC, mongugay commented on test/list_extensions_test.dart
> +
Добавил

2021-10-15 08:29 UTC, merged